### ISSUE TITLE
Shared controller and presenter

### ISSUE THREAD

**Issue by ccfiel** [ShadyBoukhary/flutter_clean_architecture#15]
@ShadyBoukhary  Is it possible to have shared controller and presenter that can be shared to  multiple views and these views have also there own controller and presenter?

![Shared controller and presenter (2)](https://user-images.githubusercontent.com/1788360/70596451-eaada080-1c20-11ea-8304-079e87f3e085.png)

**Comment by ShadyBoukhary** [comment]
Hi,

It is possible. [Here](https://github.com/ShadyBoukhary/Axion-Technologies-HnH/tree/development/lib/app/components/hhDrawer) is an example.

Thanks

**Comment by ccfiel** [comment]
thanks!
