### ISSUE TITLE
Use Provider package to improve performance of View-Controller interactions.

### ISSUE THREAD

**Issue by ShadyBoukhary** [ShadyBoukhary/flutter_clean_architecture#18]
## Improve Performance Using Provider Package
* Inject Controller into View using Provider
* Abstract `Provider.of` inside the View

**Comment by arrrrny** [comment]
This would be great

**Comment by ccfiel** [comment]
wow this could be great! :) @ShadyBoukhary

**Comment by ccfiel** [comment]
@ShadyBoukhary any idea when will this be in dev branch? :) I am eager to be the tester :)

**Comment by ShadyBoukhary** [comment]
@ccfiel soon. I'm experimenting with different ways this could be implemented. I might push something to dev tonight!

**Comment by ccfiel** [comment]
@ShadyBoukhary thanks for the update!

**Comment by emrahcetiner** [comment]
is there any update on this?

**Comment by ShadyBoukhary** [comment]
@ccfiel @emrahcetiner,
Please check pull request #30 
I've pushed some working code with the provider package. This is a work in progress so i might make some changes later.

Thanks

**Comment by ccfiel** [comment]
@ShadyBoukhary wow! thanks a lot. I will check :)

**Comment by ShadyBoukhary** [comment]
Pull request #30 merged.
