### ISSUE TITLE
clarification: globalKey usage

### ISSUE THREAD

**Issue by iRaySpace** [ShadyBoukhary/flutter_clean_architecture#22]
Currently, I am using `flutter_clean_architecture` for our mobile app. We have a scenario where we have to use a `SnackBar` to display error under `controller.initListeners()`. 

Our current implementation under `controller.initListeners()` is as follow:
```dart
getStateKey().currentState.showSnackBar(
  SnackBar(
    backgroundColor: Colors.red,
    content: Text(errors['internal_error']),
  )
);
```

In order to use the `SnackBar`, we temporarily set `State<StatefulWidget>` to `ScaffoldState`.

Are there any other scenarios where `globalKey` is used aside from it is `GlobalKey` for `Scaffold`?

Regards,

Ivan

**Comment by rafaelcmm** [comment]
```Are there any other scenarios where globalKey is used aside from it is GlobalKey for Scaffold?```

I think the globalKey is used mostly for that. I will share my implementation of the snackbar that works successfully

```dart
void initListeners() {
    ...
    presenter.getResidentsOnError = (e) {
      _setLoading(false);
      print(e);
      ScaffoldState state = getState();
      state.showSnackBar(SnackBar(content: Text('Error retrieving residents')));
      refreshUI(); // Refreshes the UI manually
    };
  }
```

**Comment by iRaySpace** [comment]
Hello @rafaelcmm 
Thank you for pointing this out. I'll implement this one.
