### ISSUE TITLE
Update rxdart to 0.23 and run flutter format to improve package health

### ISSUE THREAD

**Issue by rafaelcmm** [ShadyBoukhary/flutter_clean_architecture#23]
**Describe the solution you'd like**
Update rxdart to improve usecase, since rxdart removed `Observable` class since 0.23.

**Describe alternatives you've considered**
Update packages and start use rxdart extensions

**Comment by rafaelcmm** [comment]
@ShadyBoukhary if it's okay to you, I will start working on this issue

**Comment by ShadyBoukhary** [comment]
@rafaelcmm  I was planning on doing this soon but you can go ahead :)

**Comment by rafaelcmm** [comment]
@ShadyBoukhary already done It. Please check the PR

**Comment by rafaelcmm** [comment]
@ShadyBoukhary these changes are already on development branch. What is left to release a breaking version?

**Comment by ShadyBoukhary** [comment]
@rafaelcmm I'm going to publish a build today.

**Comment by ShadyBoukhary** [comment]
@rafaelcmm now available.

**Comment by ccfiel** [comment]
I tried to upgrade but the stream has an error ``` too many positional arguments: 0 expected, but 1 found.``` When I try to expect  it will go to dart:async library and stream should not have a parameters. Any idea how to resolve this issue? :) @ShadyBoukhary 
```
import 'dart:async';

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart';
import 'package:pedantic/pedantic.dart';

import '../../entities/user.dart';
import '../../repositories/auth_repository.dart';

class AuthenticateUserUseCase extends CompletableUseCase<User> {
  AuthRepository authRepo;
  AuthenticateUserUseCase(this.authRepo);
  @override
  Future<Stream<void>> buildUseCaseStream(User params) async {
    final StreamController<void> controller = StreamController();
    controller.add(authRepo.authenticateUser(params));
    unawaited(controller.close());
    return Stream(controller.stream);  <======= Error  
  }
}
```

**Comment by ShadyBoukhary** [comment]
Hi @ccfiel,

Just return `controller.stream` instead of `Stream(controller.stream)`. That should work!

**Comment by ccfiel** [comment]
Ok thanks! I made a PR for README https://github.com/ShadyBoukhary/flutter_clean_architecture/pull/27
