### ISSUE TITLE
how we can handle, if it is multiple usecase called?

### ISSUE THREAD

**Issue by saravananmnm** [ShadyBoukhary/flutter_clean_architecture#25]
in HomePresenter have 3 methods declaration like  Function getNext; Function getDone : Function getError; 
in case presenter have more than one usecase call, what we going todo? are we going to declare multiple methods like above mentioned.
Kindly explain about that.

**Comment by ShadyBoukhary** [comment]
@saravananmnm  It depends on what these different usecases are used for. If a presenter has multiple usecases, and each usecase does something different, then you would want to use different methods to handle the events of every usecase. 

So naturally you would need to declare multiple methods.

However, if all these usecases are somehow related and can be handled by 1 function (rare)  then you could just use the same handler for all of them. If your usecases return data used in the home page, perhaps they can be combined into 1 usecase.

If you could provide more information, I can probably give you some pointers.

Thanks

**Comment by saravananmnm** [comment]
@ShadyBoukhary Thanks for your reply.
In android i have used mvp clean architecture previously.
So here i cannot achieve those like mvp pattern.Is there any solution for that.?

In Flutter i have used kiwi for dependency injunction, So can i use that same here.


Android usecase structure
`public abstract class UseCase<T, Params> {

    private final ThreadExecutor mExecutor;
    private final PostExecutor mPostExecutor;
    private final CompositeDisposable mDisposable;
    private AndroObserver<T> mObserver;
    private PublishRelay<Long> mTrigger;

    public UseCase(ThreadExecutor executor, PostExecutor postExecution) {
        this.mExecutor = executor;
        this.mPostExecutor = postExecution;
        this.mDisposable = new CompositeDisposable();
        this.mTrigger = PublishRelay.create();
    }

    /**
     * Builds an {@link Observable} which will be used when executing the current {@link UseCase}.
     */
    public abstract Observable<T> buildUseCaseObservable(Params params);

    /**
     * Executes the current use case.
     *
     * @param observer {@link DisposableObserver} which will be listening to the observable build
     *                 by {@link #buildUseCaseObservable(Params)} ()} method.
     * @param params   Parameters (Optional) used to build/execute this use case.
     */
    public void execute(AndroObserver<T> observer, Params params) {
        mObserver = observer;
        mDisposable.clear();
        addDisposable(this.buildUseCaseObservable(params)
                .subscribeOn(Schedulers.from(mExecutor))
                .observeOn(mPostExecutor.getScheduler())
                .doOnError(error -> {
                    if (error instanceof HttpException)
                        mObserver.onRetry("Something went wrong,Please try again.", error, mTrigger);
                })
                .retryWhen(errors -> errors.flatMap((Function<Throwable, ObservableSource<?>>) error -> {
                    if (error instanceof HttpException)
                        return mTrigger;
                    else
                        return Observable.error(error);
                }))
                .subscribeWith(observer));
    }

    /**
     * Dispose from current {@link CompositeDisposable}.
     */
    public void dispose() {
        if (!mDisposable.isDisposed()) {
            mDisposable.dispose();
        }
    }

    /**
     * Dispose from current {@link CompositeDisposable}.
     */
    private void addDisposable(Disposable disposable) {
        mDisposable.add(disposable);
    }

    public AndroObserver<T> getObserver() {
        return mObserver;
    }

    public void setObserver(AndroObserver<T> observer) {
        mObserver = observer;
    }
}`

**Comment by ShadyBoukhary** [comment]
Hey @saravananmnm, I'm not entirely sure what you're trying to achieve.

What is it that you can do in MVP that you're unable to do with this package? The UseCase structure in Android is very similar.

**Comment by ShadyBoukhary** [comment]
Perhaps [this](https://github.com/ShadyBoukhary/Axion-Technologies-HnH/tree/development/lib/app/pages/home) is what you're trying to do @saravananmnm ?
