### ISSUE TITLE
How to implement unit test for use cases 

### ISSUE THREAD

**Issue by ccfiel** [ShadyBoukhary/flutter_clean_architecture#26]
I want to create unit test for use case of the sample todo app. Any idea how? @ShadyBoukhary 
```
class AddTodoUseCase
    extends UseCase<AddTodoUseCaseResponse, AddTodoUseCaseParams> {
  TodosRepository todosRepository;

  AddTodoUseCase(this.todosRepository);

  @override
  Future<Observable<AddTodoUseCaseResponse>> buildUseCaseObservable(
      AddTodoUseCaseParams params) async {
    final StreamController<AddTodoUseCaseResponse> controller =
        StreamController();
    try {
      if (params.todo.title == null || params.todo.title == "") {
        throw 'Title should not be blank!';
      } else {
        params.todo.id = todosRepository.todosLength;
        params.todo.completed = false;
        todosRepository.addTodo(params.todo);
        controller.add(AddTodoUseCaseResponse(params.todo));
        logger.finest('AddTodoUseCase successful.');
      }
      controller.close();
    } catch (e) {
      logger.severe('AddTodoUseCase unsuccessful.');
      controller.addError(e);
    }
    return Observable(controller.stream);
  }
}

/// Wrapping params inside an object makes it easier to change later
class AddTodoUseCaseParams {
  final Todo todo;

  AddTodoUseCaseParams(this.todo);
}

/// Wrapping response inside an object makes it easier to change later
class AddTodoUseCaseResponse {
  final Todo todo;

  AddTodoUseCaseResponse(this.todo);
}```

**Comment by ShadyBoukhary** [comment]
Hi,

Yes, in your test, you can create and execute the usecase. Create an Observer for the usecase. Inside the observer functions, you can write all your `expect` statements. You can mock the repository dependencies using the Mockito library.

**Comment by ccfiel** [comment]
@ShadyBoukhary  Thanks I will try to create one :)

**Comment by ccfiel** [comment]
Is this good? :) @ShadyBoukhary

test script

```
void main() {
  group('GetUserUseCase', () {
    GetUserUseCase _getUserUseCase;
    _Observer _observer;

    setUp(() {
      _getUserUseCase = GetUserUseCase(MockUsersRepository());
      _observer = _Observer();
    });

    test('Retrieves a user', () async {
      _getUserUseCase.execute(_observer, 1);
      while (!_observer.done) {
        await Future.delayed(Duration(seconds: 1));
      }
      _getUserUseCase.dispose();
    });
  });
}

class _Observer implements Observer<User> {
  bool done = false;

  @override
  void onComplete() {
    print('Complete');
  }

  @override
  void onError(e) {
    throw e;
  }

  @override
  void onNext(User response) {
    expect(response.runtimeType, User);
    expect(response.id, 1);
    expect(response.username, 'Administrator');
    done = true;
  }
}
```

mock repository

```
import 'package:mockito/mockito.dart';
import 'package:tailpos/domain/repositories/users_repository.dart';
import 'package:tailpos/domain/entities/user.dart';

class MockUsersRepository extends Mock implements UsersRepository {
  User _user;
  User _userTwo;

  List<User> _userList = [];

  MockUsersRepository() {
    _user = User(
      id: 1,
      username: 'Administrator',
      passcode: '0997',
      isActive: true,
      isAdmin: true,
    );
    _userTwo = User(
      id: 2,
      username: 'Guest',
      passcode: '1234',
      isActive: true,
      isAdmin: false,
    );
    _userList = [_user, _userTwo];
  }

  Future<User> getUser(int id) async => _userList.firstWhere((user) => user.id == id);
  Future<List<User>> get getUsers async => _userList;
}
```

**Comment by ShadyBoukhary** [comment]
This works @ccfiel !

**Comment by ccfiel** [comment]
@ShadyBoukhary thanks!

**Comment by ccfiel** [comment]
@ShadyBoukhary test is not working anymore. I tried to change Observer to Stream 
```
class _Observer implements Observer<User>
```
to
```
class _Observer implements Stream<User> 

```
but I got error 
```
Missing concrete implementations of 'Stream.any', 'Stream.asBroadcastStream'....
```
any idea how to resolve this? :)

> Is this good? :) @ShadyBoukhary
> 
> test script
> 
> ```
> void main() {
>   group('GetUserUseCase', () {
>     GetUserUseCase _getUserUseCase;
>     _Observer _observer;
> 
>     setUp(() {
>       _getUserUseCase = GetUserUseCase(MockUsersRepository());
>       _observer = _Observer();
>     });
> 
>     test('Retrieves a user', () async {
>       _getUserUseCase.execute(_observer, 1);
>       while (!_observer.done) {
>         await Future.delayed(Duration(seconds: 1));
>       }
>       _getUserUseCase.dispose();
>     });
>   });
> }
> 
> class _Observer implements Observer<User> {
>   bool done = false;
> 
>   @override
>   void onComplete() {
>     print('Complete');
>   }
> 
>   @override
>   void onError(e) {
>     throw e;
>   }
> 
>   @override
>   void onNext(User response) {
>     expect(response.runtimeType, User);
>     expect(response.id, 1);
>     expect(response.username, 'Administrator');
>     done = true;
>   }
> }
> ```
> 
> mock repository
> 
> ```
> import 'package:mockito/mockito.dart';
> import 'package:tailpos/domain/repositories/users_repository.dart';
> import 'package:tailpos/domain/entities/user.dart';
> 
> class MockUsersRepository extends Mock implements UsersRepository {
>   User _user;
>   User _userTwo;
> 
>   List<User> _userList = [];
> 
>   MockUsersRepository() {
>     _user = User(
>       id: 1,
>       username: 'Administrator',
>       passcode: '0997',
>       isActive: true,
>       isAdmin: true,
>     );
>     _userTwo = User(
>       id: 2,
>       username: 'Guest',
>       passcode: '1234',
>       isActive: true,
>       isAdmin: false,
>     );
>     _userList = [_user, _userTwo];
>   }
> 
>   Future<User> getUser(int id) async => _userList.firstWhere((user) => user.id == id);
>   Future<List<User>> get getUsers async => _userList;
> }
> ```

**Comment by ccfiel** [comment]
@ShadyBoukhary weird I just change back to observer the test pass. Disregard the issue. Test is now working again.

**Comment by ShadyBoukhary** [comment]
@ccfiel You shouldn't change it to `Stream`. The `Observer` class is not a part of RxDart. It is a part of this library's API. It's used as a listener to the streams. That's why it broke when changed from Observer to Stream. The class that was changed to `Stream` was RxDart's `Observable` class.
