### ISSUE TITLE
Controller onResumed: assertion failed context != null

### ISSUE THREAD

**Issue by iRaySpace** [ShadyBoukhary/flutter_clean_architecture#28]
Good day!

We are incorporating passcode input into our mobile application. However, we wanted to have a protected page where `the user paused and goes back to the application (onResumed triggered)` the controller will navigate to pin route.

The current code implementation goes like this.
```dart
@override
void onResumed() {
  Navigator.of(getContext()).pushReplacementNamed('/pin');
}
```

However, when we do `the user paused and goes back to the application` the second time, we encounter errors related to global keys.
```dart
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following assertion was thrown during a platform message callback:
Make sure you are using the `globalKey` that is built into the `ViewState` inside your `build()` method.
        For example:
        `key: globalKey,` Otherwise, there is no context that the `Controller` could access.
        If this does not solve the issue, please open an issue at `https://github.com/ShadyBoukhary/flutter_clean_architecture` describing 
     the error.
'package:flutter_clean_architecture/src/controller.dart':
Failed assertion: line 212 pos 12: '_globalKey.currentContext != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      Controller.getContext (package:flutter_clean_architecture/src/controller.dart:212:12)
#3      UsersController.onResumed (package:tailpos/app/pages/users/users_controller.dart:42:18)
#4      Controller.didChangeAppLifecycleState (package:flutter_clean_architecture/src/controller.dart:103:9)
#5      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:545:16)
#6      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:346:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Wondering what is your take on this.

Regards,

Ivan

**Comment by ShadyBoukhary** [comment]
Hi @iRaySpace,

Thanks for reaching out. Could you post the code in your view's `build()` method? 

Thanks,

Shady

**Comment by iRaySpace** [comment]
Hello @ShadyBoukhary,

Here is the code base used in `build()`

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: Text('User List')),
      drawer: MainDrawer(),
      body: Container(
        child: SingleChildScrollView(
          child: UsersColumn(
            users: controller.userList,
            onUserClick: (id) {
              Navigator.pushNamed(context, '/user', arguments: {'id': id});
            },
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => Navigator.pushNamed(context, '/user'),
      ),
    );
  }
```

Thanks,

Ivan

**Comment by ShadyBoukhary** [comment]
Thanks @iRaySpace,

I will try to replicate the issue.

**Comment by ShadyBoukhary** [comment]
@iRaySpace,

I could not replicate the issue on my end.

View
```dart
class HomePage extends View {
  HomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _HomePageState createState() =>
      // inject dependencies inwards
      _HomePageState(HomeController(DataUsersRepository()));
}

class _HomePageState extends ViewState<HomePage, HomeController> {
  _HomePageState(HomeController controller) : super(controller);


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: Text('User List')),
      //drawer: MainDrawer(),
      body: Container(
        child: SingleChildScrollView(
          child: Text("Test")
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () => Navigator.pushNamed(context, '/user'),
      ),
    );
  }
}
```

And in the Controller
```dart
  @override
  void onResumed() {
    print("Resumed application.");
    var context = getContext();
    print(context);
  }
```

I tried pausing and resuming the application multiple times. `getContext()` never threw an exception as the globalKey was always valid.

I'm going to need more information to resolve this issue.  Please answer the following questions.

> What version of the package are you using?
> What version of Flutter are you using?
> Where did you run the application (iOS simulator, Android simulator, device)
> What OS version is the simulator/device running?

If possible, please post your View and Controller code in full and explain the issue more in detail.

Thanks,

Shady

**Comment by iRaySpace** [comment]
Hello @ShadyBoukhary 

What version of the package are you using? 
`flutter_clean_architecture: ^1.0.8`
What version of Flutter are you using? 
`Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)`
Where did you run the application (iOS simulator, Android simulator, device) 
`Android device`
What OS version is the simulator/device running? 
`8.1.0`

**Error GIF**
![GlobalKey Error](https://user-images.githubusercontent.com/5818544/71515204-172e1180-28dd-11ea-8309-490e9e8dc5d4.gif)

The error can be found here (you may also check the whole repository): 
https://github.com/iRaySpace/todo/blob/master/lib/app/pages/home/home_controller.dart#L23

**Comment by ShadyBoukhary** [comment]
@iRaySpace,

Thanks for bringing this to my attention. The bug has been fixed. Please use the latest version of the package `2.0.2`.

Unfortunately, version `2.0.0` introduced some changes that will force you to refactor your `Domain`, as RxDart deprecated their `Observable` class and used extensions of `Stream`. Please refer to the README on how to create UseCases. The changes are minor. I will be closing this issue now. Please let me know if you have any questions.

Happy Coding,

Shady
