### ISSUE TITLE
Using and placement of Server Auth/Firebase Auth

### ISSUE THREAD

**Issue by cosinus84** [ShadyBoukhary/flutter_clean_architecture#36]
I am implementing clean architecture and I am not sure where all fits in. It seems to me that you got it all :) about this clean(gonoid) architecture. 

For auth I have two possibilities:

1. Server Auth. 
After use case login I get a token, with this token I will do all the http request that need authorization. Token is received back from usecase->presenter->controller
   a) Should this token be stored into ApiService class (single instance using service locator **get_it**) ?  
 This ApiService class should reside in **Data** and added as dependency to other repositories (almost all repositories will need it, as all http request will use this token). 
   b) All usecases->repo(http requests using the token) can receive 401 http error, this means that all the controllers should know how to handle this error, 401. Can this get handled in base controller? The controller in this case should navigate, route you back to login page

2. Firebase Auth. 
a) Should I create an adapter for firebase auth, FirebaseService that calls methods on FirebaseAuh like login, signOut, getUser...?
` Future<FirebaseUser> currentUser() {
    return _firebaseAuth.currentUser(); //_firebaseAuth is FirebaseAuth.instance
  }`
b) Should I use this class FirebaseService as dependency to repositories, when is neded (get the userId, etc...) ?
c) FirebaseService should stay in **Data** part of the clean architecture?
d) FirebaseAuth auth can be used as a stream when changes to auth occurs (FirebaseAuth.instance.onAuthStateChanged). How can I use this ? directly in controller? or follow the path controller->presenter->usecase->firebseRepo get back the stream and listen to it on the top app controller.

Thanks!

**Comment by ShadyBoukhary** [comment]
I recommend option 2.

#### Concerning option 1,

>After use case login I get a token, with this token I will do all the http request that need authorization. Token is received back from usecase->presenter->controller
Tokens or any http related data should remain in the data layer and never cross into the UI layer.

>All usecases->repo(http requests using the token) can receive 401 http error, this means that all the controllers should know how to handle this error, 401. Can this get handled in base controller? The controller in this case should navigate, route you back to login page

Yes, you can a base controller to handle such app-wide events. There are several ways to do this:
1. Create a base Controller class with a method that navigates back to the login page and have all controllers inherit from it.
2. Use a base Controller and inject it into the tree using Provider.

#### Concerning option 2,
>Should I create an adapter for firebase auth, FirebaseService that calls methods on FirebaseAuth like login, signOut, getUser...?

Yes, I recommend creating a FirebaseService, or AuthService, that handles authentication and can retrieve the current user. You can use this service as a dependency for all the usecases that need it.

>Should I use this class FirebaseService as dependency to repositories, when is neded (get the userId, etc...) ?

Yes, for example, a GetCurrentUser usecase would use this repository as a dependency.

>FirebaseService should stay in Data part of the clean architecture?

Yes, only in the data layer.

>FirebaseAuth auth can be used as a stream when changes to auth occurs (FirebaseAuth.instance.onAuthStateChanged). How can I use this ? directly in controller? or follow the path controller->presenter->usecase->firebseRepo get back the stream and listen to it on the top app controller.

This is very easy to do as Usecases are set up to use streams. 
In your `onAuthChangedUseCase`, you can set it up this way:

```dart
  @override
  Future<Stream<void>> buildUseCaseStream(_) async {
    return firebaseAuthService.getOnAuthStateChangedStream();
  }
```
where `firebaseAuthService.getOnAuthStateChangedStream()` is a method inside `FirebaseAuthService` that returns `FirebaseAuth.instance.onAuthStateChanged`.

This results in whatever Controller/Presenter tied to this usecase will be triggered whenever the auth state changes.

I definitely recommend option 2.

Please let me know if this answers your questions.

Shady

**Comment by cosinus84** [comment]
Thank you very much for your answer, helps me a lot, I highly appreciate and I hope others will find this useful.
All your explanations were very clear but remained something regarding question 1.

Concerning option 1,
After use case login I get a token, with this token I will do all the http request that need authorization. Token is received back from usecase->presenter->controller

> Tokens or any http related data should remain in the data layer and never cross into the UI layer.

To understand better:
   1. Get token from usecase back to controller, controller (maybe on the presenter) gets the token and calls saveTokenUseCase which goes back to auth repository and saves the token in ApiService.

   2. Token does not come back to controller, all that comes back is true/false if user is logged in. The "saving" of the token in ApiService instance is done by the repository 

So is wise to go with option **2** and don't bring this token business to our application logic as is some data layer internal.

Another question, question X (thank you). This situation rises because you need more information to aggregate from multiple usecases:
1. Can usecases(inside) call another usecases?  (seems bad, but switch case must be exhaustive:) )
2. Should be done in presenter, a method on the presenter can call multiple usecases (so that the controller gets final result)? 
2. Construct an aggregate with multiple entities(if is the case of an aggregate) and use a single usecase.
3. Something is fishy, calling multiple usecases in one method call from presenter means that the usecases are orphans/incomplete

Thank you

**Comment by ShadyBoukhary** [comment]
Hi @cosinus84,

>Token does not come back to controller, all that comes back is true/false if user is logged in. The "saving" of the token in ApiService instance is done by the repository by its own

Exactly, the repository in the data layer should handle the token. `True/false` are enough to indicate to the UI whether the user is signed in.

>Can usecases(inside) call another usecases? (seems bad, but switch case must be exhaustive:) )

This isn't possible with the way the package is set up. Usecases should fulfill a requirement of your software. Perhaps if you provided a specific case I can help you with how to set it up.

>Should be done in presenter, a method on the presenter can call multiple usecases (so that the controller gets final result)?

That depends on _how_ many results you're expecting.  If the function is doing *one* thing, it should not make multiple calls because that would lead the result to be fragmented across several observers. If you are expecting 1 result, only 1 usecase should be called.

>Construct an aggregate with multiple entities(if is the case of an aggregate) and use a single usecase.

I'm not sure what scenario you're referring to. I assume you're trying to create a usecase that returns multiple objects. If that is the case, then you can create an object inside the usecase file as such

```dart
class MyUseCaseResponse {
  final Object1 object1;
  final Object2 object2;
  MyUseCaseResponse(this.object1, this.object2);
}
```
You can have the usecase return the result as such. This is the correct way to do it.

>Something is fishy, calling multiple usecases in one method call from presenter means that the usecases are orphans/incomplete

Yes, you should not have to call multiple usecases _*unless*_ these usecases have completely different purposes. You might find this [usecase](https://github.com/ShadyBoukhary/Axion-Technologies-HnH/blob/development/lib/domain/usecases/location_track_usecase.dart#L88) helpful.

Let me know if you need more clarification.

Shady
