### ISSUE TITLE
[enhancement] Controller's refreshUI() function when called reloads the whole widget tree.

### ISSUE THREAD

**Issue by sanjay4one** [ShadyBoukhary/flutter_clean_architecture#43]
First of all I would like to thank you for creating such a nice plugin. It really helped me to implement a good architecture in my projects. 

It seems that this plugin uses `Provider `for the state management of the application. But one thing I have noticed that, when I call the `refreshUI `function from the `Controller`, the whole widget tree gets reloaded. I have used `BLoC `pattern earlier where using `Streams `we can update only the portion of the UI which is required to update. The same is also possible using `Provider`.

Can you please help me to understand how can we achieve the same using the `Controller `of the plugin? Also please let me know if I have missed on something.

Thanks in advance.

**Comment by ShadyBoukhary** [comment]
This is an unfortunate side effect of allowing the controller to modify the entire widget tree, as the internal implementation wraps the entire View with a ChangeNotifier. Calling `refreshUI()` will rebuild the View.

You can achieve what you want by either
1. Making stateless/stateful widgets in the tree and sharing the same controller as provided in the Readme. You can use ChangeNotifierProvider from the Provider package to listen on a specific value from the shared controller.

2. The same as above but using inline widgets.

I do have plans on providing a much easier way to refresh specific widgets in the future.

**Comment by sanjay4one** [comment]
@ShadyBoukhary Thank you for prompt response. I really appreciate it.

As you suggested, by making a smaller View/Controller pattern and controlling it from the main controller will do the purpose but for time being I will keep it as it is.

Looking forward for the feature to update specific widgets using the plugin.

Thanks again for providing such a great plugin.

**Comment by WilliamCunhaCardoso** [comment]
> This is an unfortunate side effect of allowing the controller to modify the entire widget tree, as the internal implementation wraps the entire View with a ChangeNotifier. Calling `refreshUI()` will rebuild the View.

Maybe consider using [get](https://pub.dev/packages/get) as it also provides code (Controller to View) and update specific components with .obs and is not limited as [ChangeNotifier](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) to small number of listeners
