### ISSUE TITLE
Add listen param to getController

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [ShadyBoukhary/flutter_clean_architecture#45]
**Describe the bug**
I was testing a controller call outside build and I was facing a provider error. It was requesting me to use listen false on provider call method, but getController does not provide this to me. So I decided to PR it

**To Reproduce**
1. Call getController outside build method in a stateful widget

**Expected behavior**
Provider error about listen not being false

**Screenshots**
![Screenshot from 2020-09-21 12-54-34](https://user-images.githubusercontent.com/31575772/93791470-a79a4800-fc0a-11ea-901f-c275326ffa53.png)
![Screenshot from 2020-09-21 12-52-36](https://user-images.githubusercontent.com/31575772/93791656-e3351200-fc0a-11ea-8da5-7710121c56f8.png)

**Library (please complete the following information):**
 - flutter_clean_architecture: ^3.1.0

**Smartphone (please complete the following information):**
 - Device: [Pixel Emulator]
 - OS: [Android]
 - Version [9]

**Additional context**
It is a simple optional param to add. I am doing a pr to it

**Comment by ShadyBoukhary** [comment]
Merged #46
