### ISSUE TITLE
deactivate() Lifecycle

### ISSUE THREAD

**Issue by joaopereirajp** [ShadyBoukhary/flutter_clean_architecture#55]
Could we add the deactivate() lifecycle on controller?

**Comment by rafaelcmm** [comment]
Hi @joaopereirajp! This may be solved by this PR: https://github.com/ShadyBoukhary/flutter_clean_architecture/pull/56

Please take a look.

**Comment by rafaelcmm** [comment]
Solved on 4.0.4
