### ISSUE TITLE
Controller in PreferredSizeWidget

### ISSUE THREAD

**Issue by javier-mora** [ShadyBoukhary/flutter_clean_architecture#62]
Is there a way to access the controller from the AppBar? It is not possible to use **ControlledWidgetBuilder** as it returns a **Widget** and AppBar requires a **PreferredSizeWidget** 

Example:
```
AppBar get appBar => AppBar(
        title: Text("Title"),
        backgroundColor: Colors.white,
);
```
Valid case:
```
AppBar get appBar => AppBar(
        title: ControlledWidgetBuilder<Controller>(builder: (context, controller) {
              return Text(controller.title),
        }
       backgroundColor: Colors.white,
);
```
but if I wanted to get the background color from the controller I would have to: 
```
AppBar get appBar => ControlledWidgetBuilder<Controller>(builder: (context, controller) {
        return AppBar(
                title: Text("Title"),
                backgroundColor: controller.color,
        );
});
```
and this is invalid because AppBar requires a **PreferredSizeWidget**

**Comment by rafaelcmm** [comment]
Hi @javier-mora!

Thanks for the notice. You can achieve it in some ways.

1. You can encapsulate your `View` inside the controlled widget builder (although this is not very optimal, but it works depending on your necessity)

```dart
ControlledWidgetBuilder<Controller>(builder: (context, controller) {
        return Scaffold(
			...
		)
});
```

2. You can create your own AppBar widget extending `AppBar` or `PreferredSizeWidget` and consuming the controller inside it using `FlutterCleanArchitecture.getController`

3. You can define it directly on the view (Obviously, if you do not want it to be `Controlled`)

But you are right, `ControlledWidgetBuilder` should be agnostic about the Widget type, and I will schedule an improvement on it.

Thanks for let us know, expect an enhancement soon!
