### ISSUE TITLE
Cant add AppBar via ControlledWidgetBuilder.builder 

### ISSUE THREAD

**Issue by vadimlukutin** [ShadyBoukhary/flutter_clean_architecture#67]
**Have error if add App Bar via ControlledWidgetBuilder.builder.**

final result = Scaffold(
       

```
 appBar: ControlledWidgetBuilder<CategoryGroupListController>(
          builder: (context, controller) {
            return BaseAppBar(title: controller.title);
          },
        ),
        body: columnContainer
    );
```

**Error log:**

`error: The argument type 'ControlledWidgetBuilder<CategoryGroupListController>' can't be assigned to the parameter type 'PreferredSizeWidget'. (argument_type_not_assignable at [project_name] lib/project_name/fca/app/pages/category/category_group_list/category_group_list_view.dart:62)`

**Please describe how resolve this problem?**

**Comment by ShadyBoukhary** [comment]
Seems like `PreferredSizeWidget` should be used as a mixin with ControlledWidget. We don't currently do that. You can inherit from the the ControlledWidgetBuilder and have it return a ControlledWidget that also inherits from PreferedSizeWidget. Feel free to add it to the library via a pull request or maybe @rafaelcmm would be willing to add this. It should be relatively straightforward.

**Comment by rafaelcmm** [comment]
@vadimlukutin seems to be like: https://github.com/ShadyBoukhary/flutter_clean_architecture/issues/62#issuecomment-788558161

Please take a look and check if this solves your issuel.
