### ISSUE TITLE
One Controller for multiple pages

### ISSUE THREAD

**Issue by 7snalbar** [ShadyBoukhary/flutter_clean_architecture#68]
My issue is simple

I have one controller that will serve three or more different views, when I navigate between pages the values in the controller are reset! has anyone been able to achieve the above? if yes, how?

**Comment by ShadyBoukhary** [comment]
Hi,

how did you implement this? You should be able to initialize the controller higher up the tree than the views that are using it. Then the values would not be reset. It sounds like you’re using 2 different instances of the controller. The 2 views should share the same instance.
