### ISSUE TITLE
Flutter web compatibility

### ISSUE THREAD

**Issue by massimoliani** [ShadyBoukhary/flutter_clean_architecture#7]
I'm new to flutter development and generally to dart and web development.
I read the introduction of your component and it look really nice as basic flutter development can lead to caos!

I would like to know if the framework can be used on flutter web? For web app development?
Or if is planned to be ported?

Thanks.

**Comment by ShadyBoukhary** [comment]
Currently, it only works with mobile Flutter applications (iOS and Android) because some classes extend `StatefulWidget`.

As for porting it to web, it's possible in the future depending on Flutter for Web's popularity.
