### ISSUE TITLE
[Question] About initViewState() migration

### ISSUE THREAD

**Issue by namhuman** [ShadyBoukhary/flutter_clean_architecture#73]
Hi,
First of all, Thank you for creating this library!

I was using v4.0.1 and I'm migrating my app codes to latest version.

I used initViewState() like this:

```
class DetailedDataScreen extends View {
  final String uuid;

  DetailedDataScreen(this.uuid, {Key? key});

  @override
  _DetailDataScreenState createState() =>
      _DetailDataScreenState(DetailedDataController(DataServerRepository()));
}

class _DetailDataScreenState
    extends ViewState<DetailedDataScreen, DetailedDataController> {
  _DetailDataScreenState(controller) : super(controller);

  @override
  void initViewState(DetailedDataController controller) {
    super.initState();
    controller.getDataFromServer(uuid: widget.uuid);
  }

  @override
  Widget get view => ...   // draw view about controller.someData with ControlledWidgetBuilder<>
}
```

but after v4.0.4, View can't access its controller on InitState() because initViewState() was removed.
so if I want to pass some datas (like navigation params) to controller on init timing  and execute usecase using this datas, should i use constructor of controller?

like this :
```
class DetailedDataController extends Controller {
  DetailedDataController(this._serverRepository, this._uuid);

  final ServerRepository _serverRepository;
  final String _uuid;

  SomeData? someData;

  @override
  void onInitState() {
    super.onInitState();
    getSomeDataFromServer(uuid: _uuid);
  }

  @override
  void initListeners() {}

  void getSomeDataFromServer({required String uuid}) => ...
}
```

it is unclear for me what is right way to migration.

**Comment by rafaelcmm** [comment]
> Hi,
> First of all, Thank you for creating this library!
> 
> I was using v4.0.1 and I'm migrating my app codes to latest version.
> 
> I used initViewState() like this:
> 
> ```
> class DetailedDataScreen extends View {
>   final String uuid;
> 
>   DetailedDataScreen(this.uuid, {Key? key});
> 
>   @override
>   _DetailDataScreenState createState() =>
>       _DetailDataScreenState(DetailedDataController(DataServerRepository()));
> }
> 
> class _DetailDataScreenState
>     extends ViewState<DetailedDataScreen, DetailedDataController> {
>   _DetailDataScreenState(controller) : super(controller);
> 
>   @override
>   void initViewState(DetailedDataController controller) {
>     super.initState();
>     controller.getDataFromServer(uuid: widget.uuid);
>   }
> 
>   @override
>   Widget get view => ...   // draw view about controller.someData with ControlledWidgetBuilder<>
> }
> ```
> 
> but after v4.0.4, View can't access its controller on InitState() because initViewState() was removed.
> so if I want to pass some datas (like navigation params) to controller on init timing and execute usecase using this datas, should i use constructor of controller?
> 
> like this :
> 
> ```
> class DetailedDataController extends Controller {
>   DetailedDataController(this._serverRepository, this._uuid);
> 
>   final ServerRepository _serverRepository;
>   final String _uuid;
> 
>   SomeData? someData;
> 
>   @override
>   void onInitState() {
>     super.onInitState();
>     getSomeDataFromServer(uuid: _uuid);
>   }
> 
>   @override
>   void initListeners() {}
> 
>   void getSomeDataFromServer({required String uuid}) => ...
> }
> ```
> 
> it is unclear for me what is right way to migration.

This approach LGTM if this follows your project patterns.

In our case here, we avoid to add parameters on page constructors. If any data is needed to be consumed on page, is passed as a navigation argument to be consumed on controller.

Feel free to use any strategy that looks cleaner on your project
