### ISSUE TITLE
[Question] How do I write test for the controller or presenter class?

### ISSUE THREAD

**Issue by limcheekin** [ShadyBoukhary/flutter_clean_architecture#74]
Hi there,

As I couldn't found any code example, hence I created this issue to raise my question.

I not sure whether it is more appropriate to write tests for the controller class or the presenter class.
Appreciate if you can share a code example on how to do so.

Thank you.

**Comment by ShadyBoukhary** [comment]
You typically wouldn’t write tests for controller and presenter classes, since your logic should exist inside the domain module. You should be writing tests for the domain and your data providers

**Comment by ShadyBoukhary** [comment]
Here are some samples
https://github.com/ShadyBoukhary/Axion-Technologies-HnH/tree/development/test/unit_tests

**Comment by ccfiel** [comment]
Hello @ShadyBoukhary how about a widget test? Can we write one?

**Comment by ShadyBoukhary** [comment]
Yes
https://github.com/ShadyBoukhary/flutter_clean_architecture/blob/master/test/responsive_view_test.dart

**Comment by devwela** [comment]
@ShadyBoukhary  Thanks a lot!
