### ISSUE TITLE
Unable to override `initState` on ViewState

### ISSUE THREAD

**Issue by dcdh** [ShadyBoukhary/flutter_clean_architecture#79]
**Describe the bug**
I am unable to override initState in ViewState to properlly handle animation.

**To Reproduce**
1. Create an implementation of ViewState likes it is done here https://github.com/ShadyBoukhary/Axion-Technologies-HnH/blob/development/lib/app/pages/splash/splash_view.dart#L24
2. Override the method `initState`
3. This message is displayed: `The member 'initState' is declared non-virtual in 'ViewState' and can't be overridden in subclasses.​`

**Expected behavior**
I should be able to override initState.

**Library (please complete the following information):**
 - Version [5.0.0]

**Additional context**

In `view.dart` on the method `initState` should not be `@nonVirtual`. It should be `@mustCallSuper`.

**Comment by dcdh** [comment]
We should expose _controller to from view.dart.

**Comment by ShadyBoukhary** [comment]
Feel free to open a pull request

**Comment by rafaelcmm** [comment]
@dcdh just use `onInitState` replacement life cycle
