### ISSUE TITLE
Migrate to support 2.10.3

### ISSUE THREAD

**Issue by spendres** [ShadyBoukhary/flutter_clean_architecture#83]
1. Need to migrate the example for null safety.
Version 5.0.2 example wouldn't build for me on the most recent version of Flutter. 

I worked through roughly ten issues involving null safety and deprecated APIs and the example now builds and tests pass. Version 5.0.2 created a domain dependency on flutter that this update corrects – but would like a more clear boundary between flutter and dart. Also removed deprecated pedantic and addTime in tests. All 13 flutter test pass.

Here is the output of dart migrate against version 5.0.2 of flutter_clean_architecture and Flutter 2.10.3.
[to_flutter_2.10.dart-analyze-output.txt](https://github.com/ShadyBoukhary/flutter_clean_architecture/files/8240946/to_flutter_2.10.dart-analyze-output.txt)

This could become version 5.1 if the changes are adopted.

**Comment by ShadyBoukhary** [comment]
I think this has been resolved.
