### ISSUE TITLE
Update to flutter 3.0

### ISSUE THREAD

**Issue by bssughosh** [ShadyBoukhary/flutter_clean_architecture#84]
**Describe the bug**
WidgetsBinding: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

**To Reproduce**
1. Update to latest flutter version (3.0.5)
2. Run the app 
3. A warning is thrown

**Expected behavior**
This warning can be avoided for now but should be updated

**Library (please complete the following information):**
 - Version [e.g. 5.0.2]

**Comment by bssughosh** [comment]
@ShadyBoukhary can I pick this up?

**Comment by bssughosh** [comment]
https://github.com/ShadyBoukhary/flutter_clean_architecture/pull/85

**Comment by bssughosh** [comment]
@ShadyBoukhary Once the update is live u could close this too

**Comment by ShadyBoukhary** [comment]
#85
