### ISSUE TITLE
Add support to Dart 3

### ISSUE THREAD

**Issue by RafaelPlantard** [ShadyBoukhary/flutter_clean_architecture#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Library (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ShadyBoukhary** [comment]
Will add this week

**Comment by ShadyBoukhary** [comment]
Working on this right now. Sorry for the long haitus

**Comment by ShadyBoukhary** [comment]
Added support for dart 3 @RafaelPlantard
