### ISSUE TITLE
Error: 'View' is imported from both

### ISSUE THREAD

**Issue by arrrrny** [ShadyBoukhary/flutter_clean_architecture#95]
I just upgraded flutter to 3.16.8 to fix the Xcode issue that flutter was not able to run debug on VSCode.

I am getting below error. When I am on flutter 3.7.9 there is no issue. I guess the class name "View" must be changed inside the package. 

Issue is also stated on the pub.dev/flutter page
https://pub.dev/packages/flutter_clean_architecture/score

<img width="836" alt="Screenshot 2024-01-17 at 11 55 02 PM" src="https://github.com/ShadyBoukhary/flutter_clean_architecture/assets/48218623/370bdd5f-9954-4b1a-bed3-c74edf949e42">

Error: 'View' is imported from both 'package:flutter/src/widgets/view.dart' and 'package:flutter_clean_architecture/src/view.dart'.

**Comment by ShadyBoukhary** [comment]
Fixed @arrrrny

**Comment by arrrrny** [comment]
@ShadyBoukhary Thanks MAN! I was just about to change the whole app to a new package and I saw the 6.0.0 update. Happy to see it!
